FROM node:24.10.0-bookworm-slim AS builder

WORKDIR /app

COPY package.json package-lock.json ./
# install dev dependencies
RUN npm ci
# install only production dependencies
RUN npm install

# build the app
COPY . .
RUN npm run build

FROM node:24.10.0-bookworm-slim AS runner

WORKDIR /app

COPY --from=builder /app/dist ./dist

# install serve
RUN npm install -g serve

ENV PORT=80
EXPOSE 80

CMD ["serve", "-s", "dist", "-l", "80"]
